# -*- coding: utf-8 -*-
"""UnoCard Example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eO8J5wTfnU6SMZ-H4UOJNLy36VcG1ebR
"""

class Card:
  def __init__(self, color, ability):
    self.color = color
    self.ability = ability

  def use(self, topCard):
    pass

  def __str__(self):
    return f"{self.color} {self.ability}"


class NumCard(Card):
  def __init__(self, color, number):
    super().__init__(color, "None")
    self.number = number

  def use(self, topCard):
    if topCard.ability == "None":
      if self.color == topCard.color or self.number == topCard.number:
        return True
      else:
        return False
    elif topCard.ability == "wild":
      self.color = topCard.color
      return True
    else:
      return False

  def __str__(self):
    return f"{self.color} {self.number}"

class WildCard(Card):
  def __init__(self):
    super().__init__("wild", "wild")

  def use(self, topCard):
    if topCard is not None:
      topCard.color = input("Please select a color for your wild card!")
      return True


class UnoCard(Card):
  def __init__(self, color, ability):
    super().__init__(color, ability)

hand = [NumCard("blue", 3), NumCard("yellow", 0),  WildCard(), NumCard("blue", 22), NumCard("yellow", 4), NumCard("blue", 234) ]
topCard = NumCard("yellow", 7)

for card in hand:
  if card.use(topCard):
    # print(f"{card.color} {card.number} is used")
    print(f"you can play this {card} card")